/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OclVanitygen */

#ifndef _Included_OclVanitygen
#define _Included_OclVanitygen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OclVanitygen
 * Method:    oclGenerateAddress
 * Signature: (Ljava/lang/String;IZ)I
 */
JNIEXPORT jint JNICALL Java_net_bither_utils_OclVanitygen_oclGenerateAddress
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     OclVanitygen
 * Method:    oclGetPrivateKey
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_bither_utils_OclVanitygen_oclGetPrivateKey
  (JNIEnv *, jclass);

/*
 * Class:     OclVanitygen
 * Method:    oclGetProgress
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_bither_utils_OclVanitygen_oclGetProgress
  (JNIEnv *, jclass);



/*
 * Class:     OclVanitygen
 * Method:    oclGetDifficulty
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bither_utils_OclVanitygen_oclGetDifficulty
  (JNIEnv *, jclass);


/*
 * Class:     OclVanitygen
 * Method:    getDevices
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_bither_utils_OclVanitygen_getDevices
  (JNIEnv *, jclass);

/*
 * Class:     OclVanitygen
 * Method:    oclQuit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bither_utils_OclVanitygen_oclQuit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
