/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Vanitygen */

#ifndef _Included_Vanitygen
#define _Included_Vanitygen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Vanitygen
 * Method:    generateAddress
 * Signature: (Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_net_bither_utils_Vanitygen_generateAddress
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     Vanitygen
 * Method:    getPrivateKey
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_bither_utils_Vanitygen_getPrivateKey
  (JNIEnv *, jclass);

/*
 * Class:     Vanitygen
 * Method:    getDifficulty
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_bither_utils_Vanitygen_getDifficulty
  (JNIEnv *, jclass);

/*
 * Class:     Vanitygen
 * Method:    getProgress
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_bither_utils_Vanitygen_getProgress
  (JNIEnv *, jclass);

/*
 * Class:     Vanitygen
 * Method:    quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bither_utils_Vanitygen_quit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
